name: AWS Connection Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-connection-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::038218373505:role/CryptoETL-GitHubActions-Role
          role-session-name: github-actions-test
          aws-region: ap-south-1

      - name: Test AWS connection
        run: |
          aws sts get-caller-identity
