name: AWS OIDC Connection Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::038218373505:role/CryptoETL-GitHubActions-Role
          aws-region: ap-south-1

      - name: Test AWS Connection
        run: |
          aws sts get-caller-identity
