name: OIDC Connection

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-connection-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::038218373505:role/CryptoETL-GitHubActions-Role
          role-session-name: github-actions-test
          aws-region: ap-south-1

      - name: Test AWS connection
        run: |
          echo "Testing AWS connection..."
          aws sts get-caller-identity

      - name: Test S3 bucket access
        run: |
          echo "Testing S3 bucket access..."
          aws s3api head-bucket \
            --bucket crypto-etl-prod-diwakar-2026

          echo "S3 bucket access successful!"
